django/week5/portfolio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
#    url(r'^resume/', views.resume, name='resume'),
    url(r'^resume/', include('resume.urls', namespace='resume')),
    url(r'^portfolio/', views.portfolio, name='portfolio'),
    url(r'^contact/', views.contact, name='contact'),
]

django/week5/resume/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from resume import views

app_name="resume"

urlpatterns = [
    url(r'^$', views.home, name="resume"),
]

django/week5/resume/models.py
from django.db import models

# Create your models here.

class resume(models.Model):
    first_name = models.TextField(max_length=255)
    last_name = models.TextField(max_length=255)

    def __str__(self):
        return(self.first_name)

    def get_full_name(self):
        full_name = (self.first_name + " " + self.last_name)
        return(full_name)

    def get_last_name_first_name(self):
        full_name = (self.last_name + ", " + self.first_name)
        return(full_name)

    def get_experience(self):
        return self.experience_set.all()

    def get_education(self):
        return self.education_set.all()


class experience(models.Model):
    title = models.TextField(max_length=255)
    location = models.TextField(max_length=255)
    start_date = models.DateField(max_length=255)
    end_date = models.DateField(max_length=255)
    description = models.TextField(max_length=255)
    full_name = models.ForeignKey(resume, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return(self.title)

class education(models.Model):
    institution_name = models.TextField(max_length=255)
    location = models.TextField(max_length=255)
    degree = models.TextField(max_length=255)
    major = models.TextField(max_length=255)
    gpa = models.FloatField(max_length=255)
    full_name = models.ForeignKey(resume, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return(self.institution_name)

django/week5/portfolio/views.py
from django.shortcuts import render

def home(request):
    '''
    Renders home page
    '''
    context = {}
    return(render(request, 'home.html', context))

def resume(request):
    '''
    Renders resume page
    '''
    context = {}
    return render(request, 'resume.html', context)

def portfolio(request):
    '''
    Renders portfolio page
    '''
    context = {}
    return render(request, 'portfolio.html', context)

def contact(request):
    '''
    Renders contact page
    '''
    context = {}
    return render(request, 'contact.html', context)

django/week5/resume/views.py
from django.shortcuts import render
from .models import resume, education, experience

# Create your views here.

def home(request):
    myResume = resume.objects.first()
    context = { 'myResume': myResume}
    return render(request, 'resume/home.html', context)

django/week5/resume/templates/resume/_-base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <link rel='stylesheet' href="{% static 'css/style.css' %}" />
  </head>
  <body>
      <nav>
        <a href="{% url 'home' %}">Home</a> |
        <a href="{% url 'resume' %}">Resume</a> |
        <a href="{% url 'portfolio' %}">Portfolio</a> |
        <a href="{% url 'contact' %}">Contact</a>
      </nav>

      {% block content %}
      {% endblock %}

  </body>
</html>

django/week5/resume/templates/resume/home.html
{% extends 'base.html' %}

{% block title %}Resume{% endblock %}

{% block content %}

    <h1>Education</h1>
    {% for education in my_resume.get_education.all %}
        {{education}}<br>
    {% endfor %}

    <h1>Experience</h1>
    {% for experience in my_resume.get_experience.all %}
        {{experience}}<br>
    {% endfor %}

</body>
{% endblock %}

django/week5/templates/_old-resume.html
{% extends 'base.html' %}

{% block content %}
<div class='homepage-content'>
  <div class='homepage-banner'>
    <h1>Resume</h1>
    <hr>
    <ul>
        <li>Working at TPx Communications as a VoIP Engineer</li>
        <li>Worked at DSCI Corp as a NOC Supervisor</li>
    </ul>
    <a class='button' href="">Test</a>
  </div>
</div>
{% endblock %}

django/week5/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- <link rel='stylesheet' href="{% static 'css/nav.css' %}" /> -->
    <link rel='stylesheet' href="{% static 'css/style.css' %}" />
  </head>
  <body>
      <nav>
        <a href="{% url 'home' %}">Home</a> |
        <a href="{% url 'resume:resume' %}">Resume</a> |
        <a href="{% url 'portfolio' %}">Portfolio</a> |
        <a href="{% url 'contact' %}">Contact</a>
      </nav>

      {% block content %}{% endblock %}
      {% block footer %}{% endblock %}

  </body>
</html>

django/week5/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class='homepage-content'>
  <div class='homepage-banner'>
    <h1>Contact</h1>
    <hr>
    <h4>Contact me at <a href="mailto:ckhoshatefeh@gmail.com">ckhoshatefeh@gmail.com</a></h4>
    <a class='button' href="">Test</a>
  </div>
</div>
{% endblock %}

django/week5/templates/home.html
{% extends 'base.html' %}

{% block title %}Portfolio Site{% endblock %}

{% block content %}
<div class='homepage-content'>
  <div class='homepage-banner'>
    <h1>Home</h1>
    <hr>
    <h4>Welcome to my portfolio home!</h4>
    <a class='button' href="">Test</a>
  </div>
</div>
{% endblock %}

django/week5/templates/portfolio.html
{% extends 'base.html' %}

{% block title %}My Portfolio{% endblock %}
{% load static %}

{% block content %}
<link rel='stylesheet' href="{% static 'css/portfolio.css' %}" />
<div class="main">

    <h1>My Portfolio</h1>

</div>
{% endblock %}